project:
  type: book
  output-dir: docs
book:
  title: "Quantifying Life"
  author: "Dmitry Kondrashov"
  date: "12/23/2022"
  chapters:
    - index.qmd
    - counting.qmd
    - functions.qmd
    - descriptive.qmd
    - probdist.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

