project:
  type: book
  output-dir: docs
book:
  title: "Quantifying Life"
  author: "Dmitry Kondrashov"
  cover-image: Kondrashov_Comp.jpeg
  favicon: Kondrashov_Comp.jpeg
  twitter-card: true
  search: true
  repo-url: https://github.com/dkon1/quant_life_quatro
  downloads: [pdf, epub]
  site-url: https://dkon1.github.io/quant_life_quatro
  page-navigation: true
  chapters:
    - index.qmd
    - counting.qmd
    - functions.qmd
    - descriptive.qmd
    - probdist.qmd
    - linreg.qmd
    - independence.qmd
    - hypo_test.qmd
    - bayes.qmd
    - sampling.qmd
    - lindiff.qmd
    - graph_odes.qmd
    - ode_sols.qmd
    - markov_model.qmd
    - markov_evol.qmd
    - markov_stat.qmd
    - markov_eigen.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

