<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantifying Life - 6&nbsp; Independence</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./hypo_test.html" rel="next">
<link href="./linreg.html" rel="prev">
<link href="./Kondrashov_Comp.jpeg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Quantifying Life - 6&nbsp; Independence">
<meta name="twitter:description" content="In the first part of the book we learned how to describe data sets and probability distributions of random variables.">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Independence</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantifying Life</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/dkon1/quant_life_quatro" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Download" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-download"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Quantifying-Life.pdf">
            <i class="bi bi-bi-file-pdf pe-1"></i>
          Download PDF
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Quantifying-Life.epub">
            <i class="bi bi-bi-journal pe-1"></i>
          Download ePub
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./counting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Arithmetic and variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Functions and their graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing data sets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probdist.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random variables and distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linreg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./independence.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Independence</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypo_test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prior knowledge and Bayesian thinking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling distribution and estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lindiff.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Linear difference equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graph_odes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graphical analysis of ordinary differential equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ode_sols.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Solutions of ordinary differential equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./markov_model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Markov models with discrete states</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./markov_evol.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Probability distributions of Markov chains</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./markov_stat.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Stationary distributions of Markov chains</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./markov_eigen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dynamics of Markov models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#contingency-tables-to-summarize-data" id="toc-contingency-tables-to-summarize-data" class="nav-link active" data-scroll-target="#contingency-tables-to-summarize-data"><span class="toc-section-number">6.1</span>  Contingency tables to summarize data</a></li>
  <li><a href="#conditional-probability" id="toc-conditional-probability" class="nav-link" data-scroll-target="#conditional-probability"><span class="toc-section-number">6.2</span>  Conditional probability</a>
  <ul class="collapse">
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">6.2.1</span>  Exercises</a></li>
  </ul></li>
  <li><a href="#independence-of-events" id="toc-independence-of-events" class="nav-link" data-scroll-target="#independence-of-events"><span class="toc-section-number">6.3</span>  Independence of events</a>
  <ul class="collapse">
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="toc-section-number">6.3.1</span>  Exercises</a></li>
  <li><a href="#product-rule" id="toc-product-rule" class="nav-link" data-scroll-target="#product-rule"><span class="toc-section-number">6.3.2</span>  product rule</a></li>
  </ul></li>
  <li><a href="#independence-of-variables" id="toc-independence-of-variables" class="nav-link" data-scroll-target="#independence-of-variables"><span class="toc-section-number">6.4</span>  Independence of variables</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Independence</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>Unconnected and free<br>
No relationship to anything.<br>
– They Might Be Giants, <em>Unrelated Thing</em></p>
</blockquote>
<p>In the first part of the book we learned how to describe data sets and probability distributions of random variables. So far we have not discussed how two or more variables may influence each other, and the next four chapters will be devoted to relationships between two variables. Many experiments in biology result in observations that naturally fall into a few categories, for example: sick or healthy patients, presence or absence of a mutation, etc. The resulting data sets are called <em>categorical</em>. Unlike numerical data sets that we will investigate later in chapters 8 and 9, they are not usually represented by numbers. Although it is possible, for instance, to denote mutants with the number 1 and wild type with 0, such designation does not add any value. Categorical variables require different tools for analysis than numerical ones; one cannot compute a linear regression between two categorical variables, because there is no meaningful way to place categories on axes. In this chapter you will learn the following:</p>
<ul>
<li><p>notion of conditional probability</p></li>
<li><p>definition of independence for events and random variables</p></li>
<li><p>produce a categorical data table</p></li>
<li><p>compute a table of expected values based on independence</p></li>
</ul>
<section id="contingency-tables-to-summarize-data" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="contingency-tables-to-summarize-data"><span class="header-section-number">6.1</span> Contingency tables to summarize data</h2>
<p>What kind of relationship can there be between categorical variables? It cannot be expressed in algebraic form, because without numeric values we cannot talk about a variable increasing or decreasing. Instead, the question is, does one variable being in a particular category have an effect on which category the second variable falls into? Let us say you want to know whether the age of the mother has an effect on the child having trisomy 21 (a.k.a. Down’s syndrome), a genetic condition in which an embryo receives three chromosomes 21 instead of the normal two. The age of the mother is a numerical variable, but it can be classified into two categories: less than 35 and 35 or more years of age. The trisomy status of a fetus is clearly a binary, categorical variable: the fetus either has two chromosomes 21 or three.</p>
<p>The data are presented in a two-way or <em>contingency table</em>, which is a common way of presenting a data set with two categorical variables. The rows in such tables represent different categories of one variable and the columns represent the categories of the other, and the cells contain the data measurements of their overlaps. Table <span class="math inline">\(\ref{tab:data_table_DS_age}\)</span> shows a contingency table for the data set on Down’s syndrome and maternal age, in which the rows represent the two categories of maternal age and the columns represent the presence or absence of the syndrome. Each internal cell (as opposed to the total counts on the margins) corresponds to the number of measurement where both variables fall into the specified category, for instance the number of fetuses with the syndrome and a mother under 35 is 28.</p>
<table class="table">
<thead>
<tr class="header">
<th>Maternal age</th>
<th>No DS</th>
<th>DS</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 35</td>
<td>29,806</td>
<td>28</td>
<td>29,834</td>
</tr>
<tr class="even">
<td>&gt;= 35</td>
<td>8,135</td>
<td>64</td>
<td>8,199</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>37,941</td>
<td>92</td>
<td>38,033</td>
</tr>
</tbody>
</table>
<p>Contingency table for maternal age and incidence of Down’s syndrome. Numbers represent counts of patients belonging to both categories in the row and the column. DS = Down’s syndrome. From .</p>
<p>Once the data are organized into a contingency table, we can address the main question stated above: does the age of the mother have an effect on whether a fetus inherits three chromosomes 21? Perhaps the first approach that suggests itself is to compare the fraction of mothers carrying a fetus with DS for the two age categories. In this case, the fraction for the under-35 category is <span class="math inline">\(28/29834 \approx 0.00094\)</span>, while for the 35-and-over category the fraction is <span class="math inline">\(64/8199 \approx 0.0078\)</span>. The two fractions are different by almost a factor of 10, which suggests a real difference between the two categories. However, all data contain an element of randomness and a pinch of error, thus there needs to be quantifiable way of deciding what constitutes a real effect. But to determine if there is a relationship, we first have to define what it means to not have one.</p>
</section>
<section id="conditional-probability" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="conditional-probability"><span class="header-section-number">6.2</span> Conditional probability</h2>
<p></p>
<p>Let us return to the abstract description of probability introduced in section 8.1. There we used the notion of sample space and its subsets, called events, to describe collections of experimental outcomes. Suppose that you have some information about a random experiment that restricts the possible outcomes to a particular subset (event). In other words, you have ruled out some outcomes, so the only possible outcomes are those in the complementary set. This will affect the probability of other events in the sample space, because your information may have ruled out some of the outcomes in that event as well.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>For two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> in a sample space <span class="math inline">\(\Omega\)</span> with a probability measure <span class="math inline">\(P\)</span>, the probability of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span>, called the <em>conditional probability</em> is defined as: <span class="math display">\[P(A|B) = \frac{P(A\&amp; B)}{P(B)}\]</span></p>
</div>
</div>
<p><span class="math inline">\(A \&amp; B\)</span> represents the intersection of events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, also known as <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, the event that consists of all outcomes that are in both <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>. In words, given the knowledge that an event <span class="math inline">\(B\)</span> occurs, the sample space is restricted to the subset <span class="math inline">\(B\)</span>, which is why the denominator in the definition is <span class="math inline">\(P(B)\)</span>. The num`erator is all the outcomes we are interested in, which is <span class="math inline">\(A\)</span>, but since we are now restricted to <span class="math inline">\(B\)</span>, the numerator consists of all the elements of <span class="math inline">\(A\)</span> which are also in <span class="math inline">\(B\)</span>, or <span class="math inline">\(A \&amp; B\)</span>. The definition makes sense in two extreme cases: if <span class="math inline">\(A = B\)</span> and if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are mutually exclusive:</p>
<ul>
<li><span class="math inline">\(P(B|B) = P(B \&amp; B) /P(B) = P(B)/P(B) = 1\)</span> (probability of <span class="math inline">\(B\)</span> given <span class="math inline">\(B\)</span> is 1)</li>
<li>if <span class="math inline">\(P(A\&amp; B) =0\)</span>, then <span class="math inline">\(P(A|B) = 0/P(B) = 0\)</span> (if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are mutually exclusive, then probability of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span> is 0)</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch6/cond_prob_tikz.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">A Venn diagram of the sample space of all people with two events: tall people (<span class="math inline">\(A\)</span>) and those who like tea (<span class="math inline">\(B\)</span>) with probabilities of <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span> and their intersection indicated.</figcaption><p></p>
</figure>
</div>
<p>There are some common misunderstandings about conditional probability, which are usually the result of discrepancies between everyday word usage and precise mathematical terminology. First, the probability of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span> is not the same as probability of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>. These concepts seem interchangeable because the statement “what are the odds of finding a tall person who likes tea?” is hard to distinguish from ‘’what are the odds that a person who is tall likes tea?’’ The difference in these concepts can be illustrated using a Venn diagram, shown in figure <span class="math inline">\(\ref{fig:ch6_cond_prob}\)</span>. Based on the probabilities indicated there, the probability of randomly selecting a person who is both tall and likes tea is <span class="math inline">\(P(A \&amp; B) = 0.1\)</span>, while the probability that a tea drinker is tall is <span class="math inline">\(P(A | B) = 0.1/0.3 = 1/3\)</span>, which are different values.</p>
<p>A similar misconception is to be cavalier about the order of conditionality. In general, <span class="math inline">\(P(A | B) \neq P(B |A)\)</span>, except in special cases. Going back to the illustration in figure <span class="math inline">\(\ref{fig:ch6_cond_prob}\)</span>, the probability that a tea drinker is tall <span class="math inline">\(P(A | B) = 1/3\)</span> is the different than the probability that a tall person is a tea drinker <span class="math inline">\(P(B|A) = 0.1/0.5 = 0.2\)</span>. One must take care when interpreting written statements to carefully distinguish what is known and what remains under investigation. In the statement <span class="math inline">\(P(A | B)\)</span>, <span class="math inline">\(B\)</span> represents what is known, and <span class="math inline">\(A\)</span> represents what is still to be investigated.</p>
<p><strong>Example.</strong> Let us return to the data set in the previous section. Data table <span class="math inline">\(\ref{tab:data_table_DS_age}\)</span> describes a sample space with four outcomes and several different events. One can calculate the probability of a fetus having Down’s syndrome (event) based on the entire data set of 38,033 mothers, and 92 total cases of DS, so the probability is <span class="math inline">\(92/38,033 \approx 0.0024\)</span>. Similarly, we can calculate the probability of a mother being above 35 as <span class="math inline">\(8,199/ 38,033 \approx 0.256\)</span>.</p>
<p>Now we can calculate the conditional probability of a mother over 35 having a DS fetus, but first we have to be clear about what information is known and what is not. If the age of the mother is known to be over 35 (mature age or MA), then we calculate <span class="math inline">\(P(DS | MA) = 64/8,199 \approx 0.008\)</span>. Notice that the denominator is restricted by the information that the mother is over 35, and thus only women in that category need to be considered for the calculation.</p>
<p>On the other hand, if we have the information that the fetus has DS, we can calculate the reversed conditional probability, what is the probability that a fetus with DS has a mother above age 35? <span class="math inline">\(P(MA | DS) = 64/92 \approx 0.7\)</span>. Notice that is both calculations the numerators are the same, since they both are the intersection between the two events, but the denominators are different, because they depend on which event is given.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch6/mendel_flowers.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Punnet square of a cross of two heterozygous pea plants showing the possible genotypes and phenotypes of offspring (figure by Madprime in public domain via Wikimedia Commons.)</figcaption><p></p>
</figure>
</div>
<section id="exercises" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">6.2.1</span> Exercises</h3>
<p>In figure <span class="math inline">\(\ref{fig:mendel_flowers}\)</span> there is a table of genotypes from the classic Mendelian experiment with genetics and color of pea flowers. The parents are both heterozygous, meaning each has a copy of the dominant (purple) allele B and the recessive (white) allele b. The possible genotypes of offspring are shown inside the square, and all four outcomes have equal probabilities. Based on this information, answer the following questions.</p>
<ol type="1">
<li><p>What is the probability of an offspring having purple flowers? white flowers?</p></li>
<li><p>What is the probability of an offspring having genotype <span class="math inline">\(BB\)</span>? genotype <span class="math inline">\(Bb\)</span>? genotype <span class="math inline">\(bb\)</span>?</p></li>
<li><p>What is the probability of an offspring having genotype <span class="math inline">\(BB\)</span>, given that its flowers are purple?</p></li>
<li><p>What is the probability of an offspring having genotype <span class="math inline">\(Bb\)</span>, given that its flowers are purple?</p></li>
<li><p>What is the probability of an offspring having genotype <span class="math inline">\(BB\)</span>, given that its flowers are white?</p></li>
<li><p>What is the probability of an offspring having genotype <span class="math inline">\(Bb\)</span>, given that its flowers are white?}</p></li>
<li><p>What is the probability of an offspring having purple flowers, given that its genotype is <span class="math inline">\(BB\)</span>?</p></li>
</ol>
</section>
</section>
<section id="independence-of-events" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="independence-of-events"><span class="header-section-number">6.3</span> Independence of events</h2>
<p>We first encountered the notion of independence in chapter 3, where two events were said to be independent if they did not affect each other. The mathematical definition uses the language of conditional probability to make this notion precise. It says that <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if given the knowledge of <span class="math inline">\(A\)</span>, the probability of <span class="math inline">\(B\)</span> remains the same, and vice versa.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are <em>independent</em> if <span class="math inline">\(P(A|B) = P(A)\)</span>, or equivalently if <span class="math inline">\(P(B|A) = P(B)\)</span>.</p>
</div>
</div>
<p>Independence is not a straightforward concept. It may be confused with mutual exclusivity, as one might surmise that if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> have no overlap, then they are independent. That however, is false by definition, since <span class="math inline">\(P(A|B)\)</span> is 0 for two mutually exclusive events. The confusion stems from thinking that if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are non-overlapping, then they do not influence each other. But the notion of influence in this definition is about information; so of course if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are mutually exclusive, the knowledge that one of them occurs has an influence of the probability of the other one occurring.</p>
<p>A useful way to think about independence is in terms of fractions of outcomes. The probability of <span class="math inline">\(A\)</span> is the fraction of outcomes out of the entire sample space which is in <span class="math inline">\(A\)</span>, while the probability of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span> is the fraction of outcomes in <span class="math inline">\(B\)</span> which are also in <span class="math inline">\(A\)</span>. The definition of independence equates the two fractions, therefore, if <span class="math inline">\(A\)</span> occupies 1/2 of sample space, in order for <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> to be independent, events in <span class="math inline">\(A\)</span> must constitute 1/2 of the event <span class="math inline">\(B\)</span>. In the illustration in figure <span class="math inline">\(\ref{fig:ch6_cond_prob}\)</span>, the fraction of tall people is 0.5 of the sample space, but the fraction of tea-drinkers who are tall is <span class="math inline">\(0.1/0.3=1/3\)</span>. Since the two fractions are different, <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not independent.</p>
<p><img src="ch6/indep_ex1.png" class="img-fluid" alt="Example of two events inside a sample space that are mutually exclusive"> <img src="ch6/indep_ex2.png" class="img-fluid" alt="Example of two events inside a sample space that are partially overlapping"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch6/indep_ex3.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Illustration of two events inside a sample space where one is entirely contained in the other</figcaption><p></p>
</figure>
</div>
<section id="exercises-1" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">6.3.1</span> Exercises</h3>
<p>Consider three examples of events and their intersections in figure <span class="math inline">\(\ref{fig:ch6_indep_ex}\)</span>.</p>
<ol type="1">
<li><p>Based on the two non-overlapping (mutually exclusive) events, calculate the conditional probability <span class="math inline">\(P(A|B)\)</span> and compare it with <span class="math inline">\(P(A)\)</span>. Are <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> independent?</p></li>
<li><p>Based on the two partially overlapping events, calculate the conditional probability <span class="math inline">\(P(A|B)\)</span> and compare it with <span class="math inline">\(P(A)\)</span>. Are <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> independent?</p></li>
<li><p>Based on the two completely overlapping events, calculate the conditional probability <span class="math inline">\(P(A|B)\)</span> and compare it with <span class="math inline">\(P(A)\)</span>. Are <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> independent?</p></li>
</ol>
</section>
<section id="product-rule" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="product-rule"><span class="header-section-number">6.3.2</span> product rule</h3>
<p>The definition of independence is abstract, but it has a direct consequence of great computational value. From the definition of conditional probability, <span class="math inline">\(P(A|B) = P(A\cap B)/P(B)\)</span>, and if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent then <span class="math inline">\(P(A|B)\)</span> can be replaced with <span class="math inline">\(P(A)\)</span>, leading to the expression <span class="math inline">\(P(A) = P(A\&amp; B)/P(B)\)</span>. Multiplying both sides by <span class="math inline">\(P(B\)</span>) gives us the formula called the <em>product rule</em>, which states that for two independent events the probability of both of them occuring is the product of their separate probabilities:</p>
<p><span class="math display">\[
P(A \&amp; B) = P(B)P(A)
\]</span></p>
<p>The product rule is extremely useful for computing probability distributions of complicated random variables. Recall that the binomial distribution, which we saw in section <span class="math inline">\(\ref{sec:math4_2}\)</span> is based on a string of <span class="math inline">\(n\)</span> Bernoulli trials which are independent of each other, which allows the calculation of the probability of a string of successes and failures, or heads/tails, etc. In practice, independence between processes is rarely true in the idealized mathematical sense. However, computing the probability of two random variables without independence is extremely difficult, so it is useful to make the independence assumption and then test it against the data. If it stands up, you have a good predictive model, and if it does not, you have learned that two processes are somehow linked, which is very useful.</p>
</section>
</section>
<section id="independence-of-variables" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="independence-of-variables"><span class="header-section-number">6.4</span> Independence of variables</h2>
<p>The product rule enables us to extend the notion of independence from events to variables. The concepts of independence is the same in both contexts, since the probability of a value <span class="math inline">\(x\)</span> of a random variable <span class="math inline">\(X\)</span> corresponds to the probability of the event that gets mapped to <span class="math inline">\(x\)</span> by the variable. In order to make independence applicable to variables, the condition must hold true for all possible values of both random variables. That way, knowing the value of one variable has no effect on the probability of the other. In order to make it simpler to calculate, we will use the product rule as the equivalent condition for independence:</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are <em>independent</em> if for all possible values of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> it is true that <span class="math display">\[ P(X=a \&amp; Y=b) = P(X=a)P(Y=b)\]</span></p>
</div>
</div>
<p>This allows us to address the question posed at the beginning of the chapter: how can one determine whether a data set has independent variables? The definition allows us to calculate what we would expect if the variables were independent. Given a data set in the form of a contingency table, such as table <span class="math inline">\(\ref{tab:data_table_DS_age}\)</span>, we can first calculate the probabilities of the two variables separately, and then from that predict the probabilities of the two variables together.</p>
<p><strong>Example.</strong> Let us calculate the expected probabilities and frequencies of Down’s syndrome in pregnant women in the two age categories. First, compute the probabilities of having Down’s syndrome (and not having it), based on all the pregnancies in the data set: <span class="math inline">\(P(DS) = 92/38033 \approx 0.002419\)</span>; the complementary probability is <span class="math inline">\(P(no \ DS) = 1 - P(DS)\)</span>. Similarly, we can calculate the probability that a pregnant woman is 35 or over, based on the entire data set (let’s denote this event <span class="math inline">\(MA\)</span> for mature age). <span class="math inline">\(P(MA) = 8199/38033 \approx 0.21558\)</span>; the complementary probability is <span class="math inline">\(P(YA) = 1 - P(MA)\)</span> (<span class="math inline">\(YA\)</span> stands for young age).</p>
<p>These separate probabilities were calculated from the data, and now we can use them to calculate the predicted probabilities of different outcome, based on the assumption of independence. The probability of a mature-age woman having a pregnancy with Down’s syndrome, based on the product rule is <span class="math inline">\(P(MA \&amp; DS) \approx 0.0024 \times 0.216 = 0.000518\)</span>. Similarly, we can calculate the probabilities of the other three outcomes: $P(YA &amp; DS) $; <span class="math inline">\(P(MA \&amp; no \ DS) \approx 0.2156\)</span>; <span class="math inline">\(P(YA \&amp; no \ DS) \approx 0.782\)</span>.</p>
<p>These probabilities are the predictions based on the assumption that the two variables are independent. To compare the predictions with the data, we need to take one more step: convert the probabilities into counts, or frequencies of each occurrence. Since the probability is a fraction out of all outcomes, to generate the predicted frequency we need to multiply the probability by the total number of data points, in this case pregnant patients. The results of this calculation are seen in table <span class="math inline">\(\ref{tab:exp_table_DS_age}\)</span> with expected frequencies shown instead of experimental observations.</p>
<table class="table">
<thead>
<tr class="header">
<th>Maternal age</th>
<th>No DS</th>
<th>DS</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 35</td>
<td>29,761.8</td>
<td>72.2</td>
<td>29,834</td>
</tr>
<tr class="even">
<td>&gt;= 35</td>
<td>8,179.2</td>
<td>19.8</td>
<td>8,199</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>37,941</td>
<td>92</td>
<td>38,033</td>
</tr>
</tbody>
</table>
<p>Expected frequencies of Down’s syndrome for two different age groups of mothers, assuming that age and Down’s syndrome are independent.</p>
<p>Notice that expected frequencies do not need to be integers, because they are the result of prediction and not a data measurement. Now that we have a prediction, we can compare it with the measurements in the data table <span class="math inline">\(\ref{tab:data_table_DS_age}\)</span>. The numbers are substantially different, and we can see that the predicted frequency of Down’s syndrome for women under 35 is larger than the frequencies for women at or above 35, due to the larger fraction of patients in the younger age group. We can calculate the differences between the <em>observed</em> and <em>expected</em> contingency tables to measure how much reality differs from the assumption of independence:</p>
<table class="table">
<thead>
<tr class="header">
<th>Maternal age</th>
<th>No DS</th>
<th>DS</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 35</td>
<td>44.2</td>
<td>-44.2</td>
<td>29,834</td>
</tr>
<tr class="even">
<td>&gt;= 35</td>
<td>-44.2</td>
<td>44.2</td>
<td>8,199</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>37,941</td>
<td>92</td>
<td>38,033</td>
</tr>
</tbody>
</table>
<p>Differences between the observed frequencies of Down’s syndrome for different maternal ages and the expected frequencies based on the assumption of independence.</p>
<p>The table of differences shows that the observed frequency of DS in the data set are higher than expected by 44.2 for women above 35 years of age and is lower than expected by the same number for women below age 35. This demonstrates that mathematically speaking, the two variables of age and DS are not independent.</p>
<p>However, real data is messy and subject to randomness of various provenance. First, there is sampling error that we explored in chapter 9, which means that samples from two perfectly independent variables can and will differ from expected frequencies. Second, measurement errors or environmental noise can contribute more randomness to the data. Thus, simply checking that observed frequencies are different from expected is not enough to conclude that the variables are not independent. We need a method to decide what scale of differences is enough to declare that there is an effect e.g.&nbsp;of maternal age on the likelihood of DS. To do this, we leave the cozy theoretical confines of probability and venture into the wild and treacherous world of statistics.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./linreg.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./hypo_test.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>